package com.foodordering.auth;

public enum AdminPermission {
    NOTICE_MANAGE,
    USER_STATUS_UPDATE,
    MENU_MANAGE,
    ORDER_STATUS_UPDATE,
    FEEDBACK_STATUS_UPDATE,
    SUPPORT_TICKET_STATUS_UPDATE,
    TABLE_MANAGE,
    STATS_VIEW,
    SETTINGS_MANAGE,
    ADMIN_USER_MANAGE,
    AUDIT_LOG_VIEW
}
